version: '3'

services:
  workspace:
    image: pilot114/base-workspace72
    volumes:
      - "./:/var/www/wshell"
    ports:
      - "8080:8080"
    tty: true
    working_dir: /var/www/wshell
  nginx:
    restart: always
    image: pilot114/base-nginx
    volumes:
      - "./wshell.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/wshell"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=wshell.local
    command: ['nginx', '-g', 'daemon off;']
    depends_on:
      - php
  php:
    restart: always
    image: pilot114/base-php-wshell
    volumes:
      - "./:/var/www/wshell"
  redis:
    restart: always
    image: redis:5.0.5
    ports:
      - "6379:6379"
  mongo:
    restart: always
    image: mongo:4.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
  # GO services
  wamp:
    restart: always
    image: pilot114/base-nexus
    ports:
      - "8081:8081"
  vkstream:
    restart: always
    image: pilot114/base-stream-vk
    ports:
      - "8888:8888"
      - "8889:8889"
